"""Evidence-Based Reasoning Engine.

Consumes structured evidence packets strictly generated by Layer 1 (Acoustic/Deterministic)
and Layer 2 (ML/Semantic NLP), synthesizing timestamp-anchored recommendations without
unsupported psychological claims.
"""

from typing import List, Dict, Any, Optional
from backend.app.utils.logger import logger


class FeedbackSynthesizer:
    """Produces evidence-backed communication feedback."""

    @classmethod
    def synthesize_feedback(
        cls,
        metrics_summary: Dict[str, Any],
        timeline: List[Dict[str, Any]],
        nlp_data: Dict[str, Any],
        transcript_segments: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Generates evidence-backed recommendations strictly anchored to data points."""
        items: List[Dict[str, Any]] = []

                # 1. Pacing & Rate Acceleration Analysis
        wpm = metrics_summary.get("wpm", 0.0)

        # Only compare windows containing meaningful speech.
        # A final recording window may contain silence because the user
        # stopped speaking before the recording itself ended. Treating
        # that as 0 WPM would create a false pacing deterioration.
        speech_windows = [
            window
            for window in timeline
            if (
    window.get("word_count", 0) > 0
    or (
        "word_count" not in window
        and window.get("wpm", 0.0) > 0.0
    )
)
        ]

        if len(speech_windows) >= 2:
            first_window = speech_windows[0]
            last_window = speech_windows[-1]

            first_wpm = first_window["wpm"]
            last_wpm = last_window["wpm"]
            delta_wpm = round(last_wpm - first_wpm, 1)

            if abs(delta_wpm) >= 20.0:
                direction = "increased" if delta_wpm > 0 else "decreased"

                window_start = last_window["window_start"]
                window_end = last_window["window_end"]

                items.append({
                    "id": f"fb-pacing-{len(items)+1}",
                    "category": "pacing",
                    "message": (
                        f"Speaking rate {direction} significantly from "
                        f"{first_wpm} WPM in the initial speech window to "
                        f"{last_wpm} WPM in the final speech window."
                    ),
                    "evidence_quote": last_window.get("transcript_snippet", ""),
                    "evidence_start": window_start,
                    "evidence_end": window_end,
                    "suggestion": (
                        "Maintain a steady baseline tempo. When concluding "
                        "a complex explanation, intentionally slow down to "
                        "emphasize key takeaways."
                    ),
                    "severity": "caution" if abs(delta_wpm) > 25.0 else "info"
                })
        
        if wpm > 175.0:
            items.append({
                "id": f"fb-pacing-{len(items)+1}",
                "category": "pacing",
                "message": f"Overall active speaking rate is rapid at {wpm} WPM (typical conversational baseline: 130?160 WPM).",
                "evidence_quote": None,
                "evidence_start": 0.0,
                "evidence_end": metrics_summary.get("duration_seconds", 0.0),
                "suggestion": "Incorporate deliberate 1-second pauses between major conceptual sections to improve listener processing bandwidth.",
                "severity": "caution"
            })
        elif 0 < wpm < 110.0:
            items.append({
                "id": f"fb-pacing-{len(items)+1}",
                "category": "pacing",
                "message": f"Overall speaking rate is measured at {wpm} WPM, indicating a deliberately measured or hesitant tempo.",
                "evidence_quote": None,
                "evidence_start": 0.0,
                "evidence_end": metrics_summary.get("duration_seconds", 0.0),
                "suggestion": "Work on fluid word-grouping and smooth sentence transitions to elevate speaking cadence toward 130 WPM.",
                "severity": "info"
            })

        # 2. Hesitation & Filler Word Analysis
        filler_density = metrics_summary.get("filler_density", 0.0)
        filler_count = metrics_summary.get("filler_count", 0)
        if filler_density > 4.0:
            top_fillers = metrics_summary.get("fillers_by_token", {})
            top_str = ", ".join(f"'{k}' ({v}x)" for k, v in sorted(top_fillers.items(), key=lambda x: x[1], reverse=True)[:3])
            items.append({
                "id": f"fb-hesitation-{len(items)+1}",
                "category": "hesitation",
                "message": f"Filler token density measured at {filler_density}% ({filler_count} total instances). Most frequent tokens: {top_str}.",
                "evidence_quote": None,
                "evidence_start": 0.0,
                "evidence_end": metrics_summary.get("duration_seconds", 0.0),
                "suggestion": "Replace verbal fillers with silent acoustic pauses. Silence signals composure and allows the listener time to absorb technical detail.",
                "severity": "caution"
            })

        # 3. Acoustic Pause Structure
        long_pauses = metrics_summary.get("long_pause_count", 0)
        avg_pause = metrics_summary.get("average_pause_seconds", 0.0)
        if long_pauses >= 3:
            items.append({
                "id": f"fb-hesitation-{len(items)+1}",
                "category": "hesitation",
                "message": f"{long_pauses} long pauses exceeding 1.2 seconds were detected (average pause duration: {avg_pause}s).",
                "evidence_quote": None,
                "evidence_start": 0.0,
                "evidence_end": metrics_summary.get("duration_seconds", 0.0),
                "suggestion": "Long pauses clustered mid-sentence usually indicate lexical retrieval hesitation. Use structured frameworks to formulate answers in advance.",
                "severity": "info"
            })

        # 4. Lexical Repetition & Vocabulary
        repetition_rate = metrics_summary.get("repetition_rate", 0.0)
        ttr = metrics_summary.get("type_token_ratio", 0.0)
        if repetition_rate > 5.0:
            items.append({
                "id": f"fb-vocabulary-{len(items)+1}",
                "category": "vocabulary",
                "message": f"Measurable phrase repetition rate is {repetition_rate}%.",
                "evidence_quote": None,
                "evidence_start": 0.0,
                "evidence_end": metrics_summary.get("duration_seconds", 0.0),
                "suggestion": "Avoid restarting phrases when refining a point. Finish the thought completely before offering clarification.",
                "severity": "info"
            })

        # 5. Semantic Coherence & Topic Transitions
        mean_coherence = nlp_data.get("mean_coherence")
        transitions = nlp_data.get("transitions", [])
        if (
    mean_coherence is not None
    and mean_coherence < 0.35
    and len(transcript_segments) > 3
):
            items.append({
                "id": f"fb-structure-{len(items)+1}",
                "category": "structure",
                "message": f"Average sentence-to-sentence semantic coherence was measured at {mean_coherence}, reflecting frequent shifts between subtopics.",
                "evidence_quote": None,
                "evidence_start": 0.0,
                "evidence_end": metrics_summary.get("duration_seconds", 0.0),
                "suggestion": "Use signposting phrases (e.g. 'First...', 'Secondly...', 'In contrast...') to explicitly link transitions between concepts.",
                "severity": "info"
            })

        if transitions:
            first_trans = transitions[0]
            items.append({
                "id": f"fb-structure-{len(items)+1}",
                "category": "structure",
                "message": f"Significant topic boundary shift detected at timestamp {first_trans['timestamp']}s (semantic drift magnitude: {first_trans['drift_magnitude']}).",
                "evidence_quote": f"Transitioned from: '{first_trans['from_text']}' to: '{first_trans['to_text']}'",
                "evidence_start": max(0.0, first_trans["timestamp"] - 3.0),
                "evidence_end": first_trans["timestamp"] + 3.0,
                "suggestion": "Provide a transitional bridge sentence before shifting to a new topic so the listener can follow the logical progression.",
                "severity": "info"
            })

        # Overall summary text
        coherence_summary = (
            f"{mean_coherence}"
            if mean_coherence is not None
            else "insufficient data"
        )

        overall_summary = (
            f"Session duration: {metrics_summary.get('duration_seconds', 0.0)}s with "
            f"{metrics_summary.get('total_words', 0)} words spoken. "
            f"Active delivery rate: {wpm} WPM. Detected "
            f"{filler_count} filler words ({filler_density}% density) "
            f"and {metrics_summary.get('pause_count', 0)} pauses. "
            f"Average semantic coherence across consecutive statements is "
            f"{coherence_summary}."
        )
        
        return {
            "overall_summary": overall_summary,
            "items": items
        }
